version: "3.2"

services:
  consul-server1:
    image: hashicorp/consul:1.15.4
    container_name: consul-server1
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0"

