version: '3.7'

networks:
  consul:
    driver: bridge
        
services:
  consul-server:
    image: consul:1.15.4
    container_name: consul-server
    restart: always
    networks:
      - consul
    ports:
      - '8500:8500'
      - '8600:8600/udp'
      - '8600:8600/tcp'
    command: 'agent -server -ui -node=server-1 -bootstrap -client=0.0.0.0'