// <auto-generated />
using System;
using MasterDataService.ORM.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterDataService.Migrations
{
    [DbContext(typeof(MasterDataRepositoryContext))]
    partial class MasterDataRepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MasterDataService.ORM.EF.Model.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CustomerId");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = new Guid("94845d16-1c44-4fc6-8af0-9042dfec41f0"),
                            Address = "123 King Street, UK",
                            Email = "alexo@gmail.com",
                            FirstName = "Alexa",
                            LastName = "Otofun"
                        },
                        new
                        {
                            CustomerId = new Guid("dd6a69a9-6922-4b4d-a617-f9e71385006b"),
                            Address = "222 West Street, EU",
                            Email = "poke222@gmail.com",
                            FirstName = "Maxima",
                            LastName = "Pokemon"
                        },
                        new
                        {
                            CustomerId = new Guid("86a34015-e1b9-499b-a517-7af31841d9f6"),
                            Address = "872 Leed Street, AU",
                            Email = "sans1@gmail.com",
                            FirstName = "Sandro",
                            LastName = "Picheno"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
