services:
  product.service:
    image: product-service:latest
    container_name: product-grpc
    restart: unless-stopped
    ports:
      - "7102:80"
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ASPNETCORE_URLS=http://+:80
      - DB_CONNECTION_STRING=Server=192.168.52.72,6001;Initial Catalog=Shopping;User ID=sa;Password=P@ssword123;Trusted_Connection=False;TrustServerCertificate=True;Persist Security Info=False;Encrypt=False
      - SERVICE_NAME=ProductService1
      - SERVICE_ID=product-service-1 
      - IP_1=192.168.52.72
      - PORT_1=7102 
      - CONSUL_SERVER_URI=http://192.168.52.72:8500
