// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductServiceNamespace.ORM.EF;

#nullable disable

namespace ProductServiceNamespace.Migrations
{
    [DbContext(typeof(ProductRepositoryContext))]
    [Migration("20240129074225_InitProductDbSample2")]
    partial class InitProductDbSample2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.ORM.EF.Model.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProductId");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("de2018fd-4e94-4a9c-83f4-e41b5114064c"),
                            Description = "Cá thu Nhật hay Cá sa ba hay sa pa, còn biết đến như là cá thu Thái Bình Dương, cá thu Nhật Bản, cá thu lam hoặc cá thu bống",
                            Name = "Ca Sa Ba"
                        },
                        new
                        {
                            ProductId = new Guid("e2a85f91-ddab-427d-91eb-4c8c74a487ff"),
                            Description = "Bắp cải hay cải bắp hay cải nồi là một loại rau chủ lực trong họ Cải, phát sinh từ vùng Địa Trung Hải. Nó là cây thân thảo, sống hai năm,",
                            Name = "Bap cai"
                        },
                        new
                        {
                            ProductId = new Guid("bcda33a3-476e-40a0-b558-0c14e7c70ed0"),
                            Description = "Khoai tây, thuộc họ Cà. Khoai tây là loài cây nông nghiệp ngắn ngày, trồng lấy củ chứa tinh bột. Chúng là loại cây trồng lấy củ rộng rãi nhất thế giới và là loại",
                            Name = "Khoai tay"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
